name: 🐞 Bug Report
description: File a bug/issue
body:
  - type: markdown
    attributes:
      value: |
        # Octopus Copilot: Bug Report
        Thanks for taking the time to fill out a bug/issue report!
        
        While the solutions engineering team will make a reasonable effort to respond to this issue, the Octopus Copilot has no Support Level Agreement (SLA).

  - type: input
    id: octopus-version
    attributes:
      label: Octopus version
      description: Please provide what version of Octopus you are currently running.
      placeholder: e.g., 2023.3.xxxx
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What actually happened?
      placeholder: Tell us what is wrong
    validations:
      required: true
  - type: textarea
    id: query
    attributes:
      label: Chat query
      description: Copy the chat query here
      placeholder: Chat query
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Chat output
      description: Copy the chat output here
      placeholder: Chat output
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: If there are specific steps that you took when you encountered the problem, please outline them here.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: more-information
    attributes:
      label: More Information
      description: Anything else that can help us solve the problem, logs, links, screenshots, suspicions, add them here.
      placeholder: Tell us more
    validations:
      required: false

