name: Find Outbound IPs
'on':
  workflow_dispatch: { }
  schedule:
    - cron: '0 0 * * *'
jobs:
  outboundips:
    name: Outbound IPs
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_APPLICATION_ID }}","clientSecret":"${{ secrets.AZURE_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Get Outbound IPs
        shell: bash
        run: |
          az functionapp show --resource-group OctopusAIAgent --name octopusaiagent --query possibleOutboundIpAddresses --output tsv
          az functionapp show --resource-group OctopusAIAgent --name octoterra --query possibleOutboundIpAddresses --output tsv